
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# MQTT
mqtt:
  broker: 192.168.1.87
  port: 1883
  discovery: true
binary_sensor:
  - platform: rpi_gpio
    ports:
      2: Temp Room
sensor:
  - platform: mqtt
    name: "BM680 - Temperature"
    state_topic: "sensor/bm680"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "BM680 - Air Quality"
    state_topic: "sensor/bm680"
    unit_of_measurement: "%"
    value_template: "{{ value_json.air_quality }}"
switch:
  - platform: rpi_gpio
    ports:
      2: Temp Room

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
